version: "3"
services:
  javaclient:
    build: ./JavaGetter
    networks:
      - helloredis-net
    depends_on:
      - redis
  java_client_setter:
    build: ./JavaSetter
    networks:
      - helloredis-net
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redisdb
    networks:
      - helloredis-net
      
networks:
  helloredis-net:
