version: "3"
services:
  javaclient:
    build: .
    network:
      - helloredis-net
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redisdb
    networks:
      - webnet
      
networks:
  helloredis-net:
